quarkus:
  log:
    # Root level (applies unless overridden by category)
    level: INFO

    console:
      enabled: false
      level: TRACE

    file:
      enabled: true
      path: logs/app.log
      level: TRACE

    category:
      "org.gautelis":
        level: DEBUG

      # Quarkus internals
      "io.quarkus":
        level: DEBUG

      # JBoss Logging facade and backend
      "org.jboss.logging":
        level: TRACE
      "org.jboss.logmanager":
        level: TRACE
      "org.jboss.logmanager.handlers":
        level: TRACE

  index-dependency:
    ipto-repo-cdi:
      group-id: org.gautelis.ipto
      artifact-id: ipto-repo-cdi
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/repo
      max-size: 10
    username: repo
    password: repo

ipto:
  repository:
    database-adapter: org.gautelis.ipto.repo.search.query.adapters.PostgresAdapter
    events-threshold: 1000
    events-listeners:
      - org.gautelis.ipto.repo.listeners.NopActionListener
    cache:
      look-behind: true
      max-size: 1000
      idle-check-interval: 60
  graphql:
    sdl-resource: /ipto.graphqls
